export const UsersDataTable = [
    {
        fullName: "Ana Jankovic",
        city: "Kragujevac",
        street: "Kneza Milosa 14",
        productionEnergy: 1500,
        consumptionEnergy: 2000,
      },
      {
        fullName: "Ivan Petrovic",
        city: "Kragujevac",
        street: "Miloja Djaka 27",
        productionEnergy: 1200,
        consumptionEnergy: 1800,
      },
      {
        fullName: "Marko Radic",
        city: "Kragujevac",
        street: "Vlade Divca 33",
        productionEnergy: 900,
        consumptionEnergy: 1100,
      },
      {
        fullName: "Jovana Milic",
        city: "Kragujevac",
        street: "Kralja Petra I 7",
        productionEnergy: 800,
        consumptionEnergy: 1300,
      },
      {
        fullName: "Milan Jovanovic",
        city: "Kragujevac",
        street: "Miloja Pavlovica 16",
        productionEnergy: 1000,
        consumptionEnergy: 1500,
      },
      {
        fullName: "Sofija Stankovic",
        city: "Kragujevac",
        street: "Kosovska 4",
        productionEnergy: 700,
        consumptionEnergy: 900,
      },
      {
        fullName: "Nikola Vujic",
        city: "Kragujevac",
        street: "Dusanova 22",
        productionEnergy: 800,
        consumptionEnergy: 1200,
      },
      {
        fullName: "Maja Nikolic",
        city: "Kragujevac",
        street: "Kneginje Milice 11",
        productionEnergy: 900,
        consumptionEnergy: 1400,
      },
      {
        fullName: "Nina Djokic",
        city: "Kragujevac",
        street: "Nikole Pasica 6",
        productionEnergy: 1100,
        consumptionEnergy: 1700,
      },
      {
        fullName: "Stefan Popovic",
        city: "Kragujevac",
        street: "Majke Jugovica 23",
        productionEnergy: 1200,
        consumptionEnergy: 1600,
      }
]